import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";
import type { Patient, PatientState } from "../types";

const mockPatients: Patient[] = [
  {
    id: "MPI-00142",
    name: "Rahul Mehta",
    age: 52,
    gender: "Male",
    dob: "14 Mar 1974",
    bloodGroup: "A+",
    phone: "+91 98765 43210",
    email: "rahul.mehta@email.com",
    address: "42, Shivaji Nagar, Pune 411005",
    emergencyContact: "Sunita Mehta (Wife) - +91 98765 43211",
    insurance: "HDFC Health - Active",
    allergies: ["Penicillin"],
    ward: "ICU-2",
    bed: "Bed 4",
    admissionDate: "20 Mar 2026",
    diagnosis: "NSTEMI with respiratory distress",
    department: "Cardiology",
    status: "Critical",
    vitals: {
      spo2: 88,
      bloodPressure: "142/90",
      heartRate: 102,
      temperature: 98.6,
      respiratoryRate: 22,
      glucose: 196,
    },
    medications: [
      { id: "m1", name: "Atorvastatin", dosage: "40mg", route: "Oral", frequency: "Once daily" },
      { id: "m2", name: "Metoprolol", dosage: "25mg", route: "Oral", frequency: "Twice daily" },
      { id: "m3", name: "Heparin", dosage: "5000 IU", route: "IV", frequency: "Every 8 hrs" },
      { id: "m4", name: "Aspirin", dosage: "81mg", route: "Oral", frequency: "Once daily" },
    ],
    timeline: [
      { id: "t1", timestamp: "Today 08:14 AM", description: "SpO₂ dropped to 88%. Supplemental O₂ initiated. Physician notified.", type: "critical" },
      { id: "t2", timestamp: "Today 06:30 AM", description: "Morning vitals recorded. BP elevated at 142/90. ECG shows sinus tachycardia.", type: "warning" },
      { id: "t3", timestamp: "Yesterday 11:00 PM", description: "Admitted to ICU-2. Initial diagnosis: NSTEMI with respiratory distress.", type: "info" },
      { id: "t4", timestamp: "Yesterday 09:40 PM", description: "Arrived at Emergency. Troponin: 0.9 ng/mL. Cardiology consult placed.", type: "success" },
    ],
    attendingDoctor: "Dr. S. Raina",
  },
  {
    id: "MPI-00189",
    name: "Ayesha Khan",
    age: 34,
    gender: "Female",
    dob: "05 Jun 1991",
    bloodGroup: "B+",
    phone: "+91 97654 32109",
    email: "ayesha.khan@email.com",
    address: "15, MG Road, Mumbai 400001",
    emergencyContact: "Imran Khan (Husband) - +91 97654 32110",
    insurance: "Star Health - Active",
    allergies: [],
    ward: "Ward 3",
    bed: "Bed 12",
    admissionDate: "19 Mar 2026",
    diagnosis: "Acute bronchitis with mild hypoxia",
    department: "Respiratory",
    status: "Observation",
    vitals: {
      spo2: 96,
      bloodPressure: "118/76",
      heartRate: 78,
      temperature: 99.1,
      respiratoryRate: 18,
      glucose: 102,
    },
    medications: [
      { id: "m1", name: "Azithromycin", dosage: "500mg", route: "Oral", frequency: "Once daily" },
      { id: "m2", name: "Salbutamol", dosage: "2.5mg", route: "Nebulizer", frequency: "Every 6 hrs" },
    ],
    timeline: [
      { id: "t1", timestamp: "Today 08:00 AM", description: "Missed morning medication dose. Nurse alert triggered.", type: "warning" },
      { id: "t2", timestamp: "Yesterday 02:00 PM", description: "Chest X-ray completed. Mild consolidation noted in right lower lobe.", type: "info" },
    ],
    attendingDoctor: "Dr. S. Raina",
  },
  {
    id: "MPI-00203",
    name: "Sunita Iyer",
    age: 61,
    gender: "Female",
    dob: "22 Sep 1964",
    bloodGroup: "O+",
    phone: "+91 96543 21098",
    email: "sunita.iyer@email.com",
    address: "8, Koramangala, Bangalore 560034",
    emergencyContact: "Ramesh Iyer (Son) - +91 96543 21099",
    insurance: "Bajaj Allianz - Active",
    allergies: ["Sulfa drugs"],
    ward: "Ward 1",
    bed: "Bed 7",
    admissionDate: "18 Mar 2026",
    diagnosis: "Post-chemotherapy monitoring",
    department: "Oncology",
    status: "Stable",
    vitals: {
      spo2: 99,
      bloodPressure: "122/80",
      heartRate: 72,
      temperature: 98.2,
      respiratoryRate: 16,
      glucose: 98,
    },
    medications: [
      { id: "m1", name: "Ondansetron", dosage: "8mg", route: "Oral", frequency: "Twice daily" },
      { id: "m2", name: "Filgrastim", dosage: "300mcg", route: "Subcutaneous", frequency: "Once daily" },
    ],
    timeline: [
      { id: "t1", timestamp: "Today 07:45 AM", description: "Lab results ready. CBC and lipid panel available for review.", type: "info" },
      { id: "t2", timestamp: "Yesterday 10:00 AM", description: "Round 3 chemotherapy completed without complications.", type: "success" },
    ],
    attendingDoctor: "Dr. S. Raina",
  },
  {
    id: "MPI-00217",
    name: "Vijay Sharma",
    age: 47,
    gender: "Male",
    dob: "30 Jan 1979",
    bloodGroup: "AB+",
    phone: "+91 95432 10987",
    email: "vijay.sharma@email.com",
    address: "23, Connaught Place, Delhi 110001",
    emergencyContact: "Meera Sharma (Wife) - +91 95432 10988",
    insurance: "Max Bupa - Active",
    allergies: [],
    ward: "OPD",
    bed: "Room 3",
    admissionDate: "21 Mar 2026",
    diagnosis: "Hypertensive urgency",
    department: "Cardiology",
    status: "Observation",
    vitals: {
      spo2: 97,
      bloodPressure: "158/100",
      heartRate: 88,
      temperature: 98.4,
      respiratoryRate: 17,
      glucose: 142,
    },
    medications: [
      { id: "m1", name: "Amlodipine", dosage: "5mg", route: "Oral", frequency: "Once daily" },
      { id: "m2", name: "Losartan", dosage: "50mg", route: "Oral", frequency: "Once daily" },
    ],
    timeline: [
      { id: "t1", timestamp: "Today 07:30 AM", description: "BP recorded at 158/100 mmHg. Medication adjusted.", type: "warning" },
    ],
    attendingDoctor: "Dr. S. Raina",
  },
  {
    id: "MPI-00231",
    name: "Priya Joshi",
    age: 29,
    gender: "Female",
    dob: "14 Aug 1996",
    bloodGroup: "B-",
    phone: "+91 94321 09876",
    email: "priya.joshi@email.com",
    address: "67, FC Road, Pune 411004",
    emergencyContact: "Amit Joshi (Father) - +91 94321 09877",
    insurance: "United Health - Active",
    allergies: ["NSAIDs"],
    ward: "ICU-1",
    bed: "Bed 2",
    admissionDate: "21 Mar 2026",
    diagnosis: "Septic shock with multi-organ dysfunction",
    department: "Emergency",
    status: "Critical",
    vitals: {
      spo2: 85,
      bloodPressure: "90/60",
      heartRate: 118,
      temperature: 103.2,
      respiratoryRate: 28,
      glucose: 210,
    },
    medications: [
      { id: "m1", name: "Norepinephrine", dosage: "0.1mcg/kg/min", route: "IV", frequency: "Continuous" },
      { id: "m2", name: "Meropenem", dosage: "1g", route: "IV", frequency: "Every 8 hrs" },
      { id: "m3", name: "Hydrocortisone", dosage: "50mg", route: "IV", frequency: "Every 6 hrs" },
    ],
    timeline: [
      { id: "t1", timestamp: "Today 06:00 AM", description: "SpO₂ dropped to 85%. Intubation considered. ICU team alerted.", type: "critical" },
      { id: "t2", timestamp: "Today 02:00 AM", description: "Admitted to ICU-1. Septic shock protocol initiated.", type: "critical" },
    ],
    attendingDoctor: "Dr. S. Raina",
  },
  {
    id: "MPI-00198",
    name: "Mohan Nair",
    age: 55,
    gender: "Male",
    dob: "03 Dec 1970",
    bloodGroup: "A-",
    phone: "+91 93210 98765",
    email: "mohan.nair@email.com",
    address: "12, MG Road, Kochi 682001",
    emergencyContact: "Lata Nair (Wife) - +91 93210 98766",
    insurance: "Oriental Insurance - Active",
    allergies: [],
    ward: "Discharged",
    bed: "—",
    admissionDate: "15 Mar 2026",
    diagnosis: "Ischemic stroke - recovered",
    department: "Neurology",
    status: "Discharged",
    vitals: {
      spo2: 98,
      bloodPressure: "128/82",
      heartRate: 68,
      temperature: 98.0,
      respiratoryRate: 15,
      glucose: 95,
    },
    medications: [
      { id: "m1", name: "Clopidogrel", dosage: "75mg", route: "Oral", frequency: "Once daily" },
      { id: "m2", name: "Rosuvastatin", dosage: "20mg", route: "Oral", frequency: "Once daily" },
    ],
    timeline: [
      { id: "t1", timestamp: "20 Mar 2026", description: "Patient discharged in stable condition. Follow-up in 2 weeks.", type: "success" },
      { id: "t2", timestamp: "17 Mar 2026", description: "MRI brain completed. No new infarcts detected.", type: "info" },
    ],
    attendingDoctor: "Dr. S. Raina",
  },
];

const initialState: PatientState = {
  patients: mockPatients,
  selectedPatient: null,
  loading: false,
  error: null,
  viewMode: "grid",
};

const patientSlice = createSlice({
  name: "patients",
  initialState,
  reducers: {
    addPatient: (state, action: PayloadAction<Patient>) => {
      state.patients.unshift(action.payload);
    },
    setSelectedPatient: (state, action: PayloadAction<Patient | null>) => {
      state.selectedPatient = action.payload;
    },
    setViewMode: (state, action: PayloadAction<"grid" | "list">) => {
      state.viewMode = action.payload;
    },
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.loading = action.payload;
    },
    setError: (state, action: PayloadAction<string | null>) => {
      state.error = action.payload;
    },
  },
});

export const {
  addPatient,
  setSelectedPatient,
  setViewMode,
  setLoading,
  setError,
} = patientSlice.actions;

export default patientSlice.reducer;